#ifndef _ERRORS_HEADER
#define _ERRORS_HEADER

#define OK												1 

#define COMMAD_NOT_FOUND								-2
#define MATRIX_NAME_NOT_FOUND							-3 
#define INVALID_INPUT_NUMBER							-4 
#define MATRIX_NOT_INITIALIZE							-5
#define MARIX_ADD_FIRST_MATRIX_PARAMETER_IS_INCORRECT	-6
#define MARIX_ADD_SECOND_MATRIX_PARAMETER_IS_INCORRECT	-7
#define MARIX_ADD_RESULT_MATRIX_PARAMETER_IS_INCORRECT	-8


#define STOP_PROGRAM  99

#endif  